// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContainerData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attachStdin property</summary>
        public bool? AttachStdin { get; set; }
        /// <summary>The env property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Env { get; set; }
#nullable restore
#else
        public List<string> Env { get; set; }
#endif
        /// <summary>The port property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Port { get; set; }
#nullable restore
#else
        public string Port { get; set; }
#endif
        /// <summary>The serverName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerName { get; set; }
#nullable restore
#else
        public string ServerName { get; set; }
#endif
        /// <summary>The serverType property</summary>
        public int? ServerType { get; set; }
        /// <summary>The tty property</summary>
        public bool? Tty { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Models.ContainerData"/> and sets the default values.
        /// </summary>
        public ContainerData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.ContainerData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.ContainerData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.ContainerData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachStdin", n => { AttachStdin = n.GetBoolValue(); } },
                { "env", n => { Env = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "port", n => { Port = n.GetStringValue(); } },
                { "serverName", n => { ServerName = n.GetStringValue(); } },
                { "serverType", n => { ServerType = n.GetIntValue(); } },
                { "tty", n => { Tty = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("attachStdin", AttachStdin);
            writer.WriteCollectionOfPrimitiveValues<string>("env", Env);
            writer.WriteStringValue("port", Port);
            writer.WriteStringValue("serverName", ServerName);
            writer.WriteIntValue("serverType", ServerType);
            writer.WriteBoolValue("tty", Tty);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
