// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Container.Item.Command;
using KiotaPosts.Client.Container.Item.Delete;
using KiotaPosts.Client.Container.Item.Edit;
using KiotaPosts.Client.Container.Item.Logs;
using KiotaPosts.Client.Container.Item.Port;
using KiotaPosts.Client.Container.Item.Restart;
using KiotaPosts.Client.Container.Item.Start;
using KiotaPosts.Client.Container.Item.Stats;
using KiotaPosts.Client.Container.Item.Status;
using KiotaPosts.Client.Container.Item.Stop;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Container.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \container\{serverName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithServerNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The command property</summary>
        public global::KiotaPosts.Client.Container.Item.Command.CommandRequestBuilder Command
        {
            get => new global::KiotaPosts.Client.Container.Item.Command.CommandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::KiotaPosts.Client.Container.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::KiotaPosts.Client.Container.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit property</summary>
        public global::KiotaPosts.Client.Container.Item.Edit.EditRequestBuilder Edit
        {
            get => new global::KiotaPosts.Client.Container.Item.Edit.EditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logs property</summary>
        public global::KiotaPosts.Client.Container.Item.Logs.LogsRequestBuilder Logs
        {
            get => new global::KiotaPosts.Client.Container.Item.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The port property</summary>
        public global::KiotaPosts.Client.Container.Item.Port.PortRequestBuilder Port
        {
            get => new global::KiotaPosts.Client.Container.Item.Port.PortRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restart property</summary>
        public global::KiotaPosts.Client.Container.Item.Restart.RestartRequestBuilder Restart
        {
            get => new global::KiotaPosts.Client.Container.Item.Restart.RestartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::KiotaPosts.Client.Container.Item.Start.StartRequestBuilder Start
        {
            get => new global::KiotaPosts.Client.Container.Item.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::KiotaPosts.Client.Container.Item.Stats.StatsRequestBuilder Stats
        {
            get => new global::KiotaPosts.Client.Container.Item.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::KiotaPosts.Client.Container.Item.Status.StatusRequestBuilder Status
        {
            get => new global::KiotaPosts.Client.Container.Item.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stop property</summary>
        public global::KiotaPosts.Client.Container.Item.Stop.StopRequestBuilder Stop
        {
            get => new global::KiotaPosts.Client.Container.Item.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Container.Item.WithServerNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithServerNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/container/{serverName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Container.Item.WithServerNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithServerNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/container/{serverName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
