// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Container.Create;
using KiotaPosts.Client.Container.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Container
{
    /// <summary>
    /// Builds and executes requests for operations under \container
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContainerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::KiotaPosts.Client.Container.Create.CreateRequestBuilder Create
        {
            get => new global::KiotaPosts.Client.Container.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the KiotaPosts.Client.container.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KiotaPosts.Client.Container.Item.WithServerNameItemRequestBuilder"/></returns>
        public global::KiotaPosts.Client.Container.Item.WithServerNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("serverName", position);
                return new global::KiotaPosts.Client.Container.Item.WithServerNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Container.ContainerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/container", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Container.ContainerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/container", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
