// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Backup.Item.Create;
using KiotaPosts.Client.Backup.Item.Delete;
using KiotaPosts.Client.Backup.Item.List;
using KiotaPosts.Client.Backup.Item.Restore;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Backup.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \backup\{serverName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithServerNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::KiotaPosts.Client.Backup.Item.Create.CreateRequestBuilder Create
        {
            get => new global::KiotaPosts.Client.Backup.Item.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::KiotaPosts.Client.Backup.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::KiotaPosts.Client.Backup.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::KiotaPosts.Client.Backup.Item.List.ListRequestBuilder List
        {
            get => new global::KiotaPosts.Client.Backup.Item.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::KiotaPosts.Client.Backup.Item.Restore.RestoreRequestBuilder Restore
        {
            get => new global::KiotaPosts.Client.Backup.Item.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Backup.Item.WithServerNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithServerNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/backup/{serverName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Backup.Item.WithServerNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithServerNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/backup/{serverName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
